### ISSUE TITLE
Brunch over Webpack?

### ISSUE THREAD

**Issue by mjsisley** [bigardone/phoenix-toggl#4]
These tributes are awesome! Thanks for them.

This really isn't an issue, but I noticed that you used webpack in phoenix-trello and are using brunch here. What was the reasoning for the switch?

**Comment by bigardone** [comment]
thanks @mjsisley! I'm glad you liked them :)
The reason for using **brunch** here instead of **webpack** was that **brunch** comes as the default static assets build tool in Phoenix, and I wanted to give it a try. Now I use it always as I find it simpler and easier to configure and use than Webpack.
Cheers!
